export const endpoints = {
  jadidlar: "/jadidlar",
  jadidById: (id) => `/jadidlar/${id}`,
  news: "/yangiliklar",
  newsById: (id) => `/yangiliklar/${id}/`,
  slider: "/slayder",
  sliderById: (id) => `/slider/${id}`,
  usefulLink: "/foydali_havolalar",
  usefulLinkById: (id) => `/foydali_havolalar/${id}`,
  collection: "/asarlar",
  newsPage: "/yangiliklar",
  meetingsById: (id) => `/kanferensiyalar/${id}/`,
  meetingsPage: "/kanferensiyalar",
  seminarsById: (id) => `/seminarlar/${id}/`,
  seminarsPage: "/seminarlar",
  collection: "/asarlar",
  collectionById: (id) => `/asarlar/${id}`,
  article: "/maqolalar",
  articleById: (id) => `/maqolalar/${id}`,
  wisewords: "/hikmatli_sozlar",
  wisewordsById: (id) => `/hikmatli_sozlar/${id}/`,
  memories: "/hotiralar", //Estaliklar
  memoriesById: (id) => `${id}/`,
  // memories: "/",//izlanishler
  // memoriesById: (id) =>`${id}/`
  arChiveLists: "/arxiv_hujjatlar",
  arChiveListsById: (id) => `/arxiv_hujjatlar/${id}/`,
  matbuot: "/maqolalar",
  matbuotById: (id) => `/maqolalar/${id}`,

  sherlar: "/sherlar",
  sherlarById: (id) => `/sherlar/${id}/`,
  disetations: "/dissertatsiya/",
  disertationsById: (id) => `/dissertatsiya/${id}/`,
  esdalik: "/hotiralar",
  esdalikById: (id) => `/hotiralar/${id}`,
  sahifalar: "/sahifalar",
  sahifalarById: (id) => `/sahifalar/${id}`,
  ishtirokchilar: "/ishtirokchilar",
  ishtirokchilarById: (id) => `/ishtirokchilar/${id}`,
  video: "/videolar",
  videoById: (id) => `/videolar/${id}/`,
  foto: "/rasmlar",
  fotoById: (id) => `/rasmlar/${id}`,
  audio: "/audiolar",
  audioById: (id) => `/audiolar/${id}`,
  search: (text) => `/search/?search=${text}`,
  footer: "/tanlovlar",
  footerById: (id) => `/tanlovlar/${id}`,
  fileDownloadId: (url, id) => `/${url}/downland/${id}`,
  login: "/token/",
  register: "/register/",
  loginWithGoogle: "/google_login/",
  // random api
  jadidRandom: "/jadidlar_random",
  arxivRandom: "/arxiv_random/",
  asarlarRandomIzlanish: "/asarlar_random_izlanish/",
  asarlarRandomTilImlo: "/asarlar_random_tilimlo/",
  asarlarRandomTurkiston: "/asarlar_random_turkiston/",
  dissertatsiyaRandom: "/dissertatsiya_random/",
  hikmatliRandom: "/hikmatli_sozlar_random/",
  hotiralarRandomIzlanish: "/hotiralar_random_izlanish/",
  hotiralarRandomTurkiston: "/hotiralar_random_turkiston/",
  maqolaRandomIzlanish: "/maqolalar_random_izlanish/",
  maqolaRandomMatbuotIqtisod: "/maqolalar_random_matbuot_iqtisod/",
  maqolaRandomTilImlo: "/maqolalar_random_tilimlo/",
  maqolaRandomTurkiston: "/maqolalar_random_turkiston/",
  sherRandomTurkiston: "/sherlar_random_turkiston/",
};
